language: ruby
cache: bundler
rvm:
 - 2.3.0

script: "bundle exec jekyll build"

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master # test the master branch only

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
